app:
  port: 3000
  log_level: info
  crontime: "*/1 * * * *"

uptimerobot:
  api_key: fake_api_key
  pattern: "%group/%index/%name"
  statuses: "2-9"

website:
  title: "服务状态"
  copyright: "楠格"
  links:
    - name: 主页
      href: https://nan.ge
    - name: 楠格
      href: https://www.nange.cn
    - name: 探针
      href: https://server.nange.cn
    - name: GitHub
      href: https://github.com/xos
